ENVIRONMENT: "development"
SERVICE_NAME: "my-service"
SERVICE_VERSION: "1.0.0"
PORT: "8080"

DATABASE:
  DIALECT: "postgres"
  HOST: "localhost"
  PORT: "5432"
  MAX_IDLE_CONNS: 10
  MAX_OPEN_CONNS: 100
  MAX_IDLE_TIME: 300
  MAX_LIFE_TIME: 3600

JWT:
  EXPIRATION_TIME: 24h

SERVER:
  READ_TIMEOUT: 15s
  WRITE_TIMEOUT: 15s